DAYS_IN_YEAR = 200
MAX_CARS = 30
START_CARS = 10

MAX_DELAY_TO_BOOK = 30
NOMINAL_DEMAND = 8
PEAK_DEMAND = 6
NOMINAL_PRICE = 30
AVG_DURATION = 4

CAR_COST_PER_DAY = 10
CAR_COST_PER_DAY_BOOKING = 10

CAR_COST_PER_ONE_OFF = 100
CAR_COST_PER_DAY_IN_CARPARK = 5

DAYS_TO_GET_A_CAR = 10
DAYS_TO_RETURN_A_CAR = 10

LEARNING_DAYS = 500000